env: standard
runtime: nodejs14
service: default

# automatic_scaling:
#   cool_down_period_sec: 180
#   cpu_utilization:
#       target_utilization: 0.9
#   max_num_instances: 2

# resources:
#   cpu: 2
#   memory_gb: 6
#   disk_size_gb: 30

# readiness_check:
#   app_start_timeout_sec: 1800

handlers:
  - url: /.*
    secure: always
    script: auto